### ISSUE TITLE
Lua thrown error in classic wow: nil GetMouseFocus() {nothing under the mouse?}

### ISSUE THREAD

**Issue by laric** [mooreatv/BetterVendorPrice#5]
Don't know if this gives you enough information.

Date: 2019-09-01 08:33:12
ID: 1
Error occured in: Global
Count: 1
Message: ...rface\AddOns\BetterVendorPrice\BetterVendorPrice.lua line 218:
   nil GetMouseFocus()
Debug:
   [C]: error()
   ...rface\AddOns\BetterVendorPrice\BetterVendorPrice.lua:218:
      ...rface\AddOns\BetterVendorPrice\BetterVendorPrice.lua:189
   [C]: ?
   [C]: OnTooltipSetItem()
   Enchantrix\EnxMain.lua:232:
      Enchantrix\EnxMain.lua:228
   [C]: ?
   ...AddOns\Auc-Advanced\Libs\LibExtraTip\LibExtraTip.lua:408:
      ...AddOns\Auc-Advanced\Libs\LibExtraTip\LibExtraTip.lua:402
   [C]: SetHyperlink()
   ...ce\AddOns\AutoBarClassic\AutoBarClassBasicButton.lua:77: TooltipShow()
   ...ce\AddOns\AutoBarClassic\AutoBarClassPopupButton.lua:62:
      ...ce\AddOns\AutoBarClassic\AutoBarClassPopupButton.lua:55
   [C]: ?
   ..\FrameXML\SecureHandlers.lua:266:
      ..\FrameXML\SecureHandlers.lua:263
   [C]: ?
   ..\FrameXML\SecureHandlers.lua:322:
      ..\FrameXML\SecureHandlers.lua:306
   (tail call): ?
Locals:
(*temporary) = "nil GetMouseFocus()"

AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  WowheadLooter, v11302
  AdvancedInterfaceOptions, v1.3.2
  ArkInventoryClassic, v10004
  ArkInventoryClassicRules, v10000
  ArkInventoryClassicSearch, v10000
  AtlasLootClassic, vv1.1.8-beta
  AucAdvanced, v8.2.6385 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucScanData, v8.2.6365 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6368 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  AutoBarClassic, v1.13.2.00
  BeanCounter, v8.2.6381 (SwimmingSeadragon)
  BetterVendorPrice, vv1.05.00-classic
  DBMCore, v1.13.5
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  DejaClassicStats, v1302r012
  Details, v
  DetailsTinyThreat, v
  Dominos, v8.2.16
  DominosCast, v
  DominosEncounter, v
  DominosProgress, v
  DominosRoll, v
  DugisGuideViewerZ, v1.012
  Enchantrix, v8.2.6392 (SwimmingSeadragon)
  InFlightLoad, v1.13.002
  Informant, v8.2.6374 (SwimmingSeadragon)
  LunaUnitFrames, v1.0
  MonkeyBuddy, v
  MonkeyLibrary, v
  MonkeyQuest, v
  MonkeyQuestLog, v
  OmniCC, v8.1.1
  Peggle, v2.2.3
  Prat30, v3.2.31
  Prat30Libraries, v
  Questie, v4.0.13 BETA
  RealMobHealth, v2.3
  SexyMap, vv2-classic
  Stubby, v8.2.6376 (SwimmingSeadragon)
  TitanClassic, v1.0.5.11302
  TitanClassicAmmo, v1.0.5.11302
  TitanClassicBag, v1.0.5.11302
  TitanClassicClock, v1.0.5.11302
  TitanClassicGold, v1.0.5.11302
  TitanClassicLocation, v1.0.5.11302
  TitanClassicLootType, v1.0.5.11302
  TitanClassicPerformance, v1.0.5.11302
  TitanClassicRepair, v1.0.5.11302
  TitanClassicVolume, v1.0.5.11302
  TitanClassicXP, v1.0.5.11302
  TomTom, vv11302-1.0.7
  tullaRange, v8.2.2
  WeakAuras, v2.14.6
  WeaponSwingTimer, v4.0.2
  WhatsTraining, v1.6
  BlizRuntimeLib_enUS v1.13.2.11302 <none>
  (ck=79e)

**Comment by mooreatv** [comment]
Yes it's when there is nothing under your mouse, which is somewhat unexpected when dealing with tooltips

Is it some other addon showing some tooltip not under the mouse ?

**Comment by mooreatv** [comment]
@laric can you try https://www.curseforge.com/wow/addons/better-vendor-price/files/2776137 and confirm it fixes it but also tell me before you upgrade how you triggered the error?

Thanks!
